name: ???

# Whether to include an example annotation in the prompt
fewshot: false

# Features to include in prompt
features: null

# GPT model to use
model: gpt-3.5-turbo-1106 # gpt-3.5-turbo / gpt-4

# Number of sentence to include in prompt
num_sentences: 10

# Number of tags to include in prompt
num_tags: 10

# Whether to re-run the labeling if already exists
relabel: true

# Use global seed
seed: ${seed}

_target_: ml_project_2_mlp.labeler.GPTLabeler
