# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: check-added-large-files

  - repo: local
    hooks:
      - id: pytest-check
        name: Run pytests
        entry: poetry run pytest
        language: system
        pass_filenames: false
        always_run: true
