# @package _global_

# Default configurations (precendence in reverse order)
defaults:
  - _self_
  - data: ???
  - labeler: ???
  - model: homepage2vec
  - logger: null
  - datamodule: default
  - callbacks: default
  - trainer: default
  - paths: default
  - hydra: default
  - extras: default
  - search: null
  - experiment: null
  - optional local: default

# Task name (determines output directory)
task_name: train

# List of tags (logged to W&B)
tags: [dev]

# Whether to also test the model on best performing model
test: true

# Random seed for reproducibility
seed: 42

# Whether to finetune the model
finetune: true
