# @package _global_

# Default configurations (precendence in reverse order)
defaults:
  - _self_
  - train_data: ???
  - train_labeler: ???
  - test_data: crowdsourced
  - test_labeler: human
  - train_datamodule: default
  - test_datamodule: default
  - model: homepage2vec
  - callbacks: default
  - trainer: default
  - paths: default
  - hydra: default
  - extras: default
  - logger: null
  - search: null
  - experiment: null
  - optional local: default

# Task name (determines output directory)
task_name: train

# List of tags (logged to W&B)
tags: [dev]

# Associated group (logged to W&B)
group: null

# Whether to also evaluate the model on the test split
eval: true

# Random seed for reproducibility
seed: 42

# Whether to finetune the model
finetune: true
