_target_: ml_project_2_mlp.model.Homepage2VecModule
model_dir: ${paths.model_dir}/homepage2vec
device: ${trainer.accelerator}
threshold: 0.5

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.0001
  weight_decay: 0.0

scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  _partial_: true
  mode: min
  factor: 0.1
  patience: 10
