defaults:
  - model_checkpoint
  - early_stopping
  - rich_progress_bar
  - _self_

model_checkpoint:
  dirpath: ${paths.output_dir}/checkpoints
  filename: "epoch_{epoch:03d}"
  monitor: "val/f1"
  mode: "max"
  auto_insert_metric_name: False

early_stopping:
  monitor: "val/f1"
  patience: 20
  mode: "max"
