# Path to root directory (Requires PROJECT_ROOT environment variable)
root_dir: ${oc.env:PROJECT_ROOT}

# Path to data directory
data_dir: ${paths.root_dir}/data/

# Path to model directory
model_dir: ${paths.root_dir}/models/

# Path to logging directory
log_dir: ${paths.root_dir}/logs/

# Path to output directory (used for checkpoints and metrics by hydra)
output_dir: ${hydra:runtime.output_dir}

# Path to working directory
work_dir: ${hydra:runtime.cwd}
