_target_: lightning.pytorch.trainer.Trainer

default_root_dir: ${paths.output_dir}

min_epochs: 0 # Minimum number of epochs to train (prevents too early stopping)
max_epochs: 30 # Maximum number of epochs

# Default accelerator and devices
accelerator: cpu
devices: 1

# Perform a validation loop every N training epochs
check_val_every_n_epoch: 1

# Ensure deterministic results (slower, but more reproducibility than just seeds)
deterministic: true
